spring.application.name=kuro-scans

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/kuroscans_db
spring.datasource.username=kuroscans
spring.datasource.password=kuroscans123

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=50
